---
title: "RWorksheet#4a_Parrenas"
author: "Erikka Jane Parrenas"
date: "2023-10-25"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#1 The table below shows the data about shoe size and height. Create a data frame
shoeSizes <- data.frame(
  shoe_Size = c(6.5 ,9.0 ,8.5 ,8.5 ,10.5 ,7.0 ,9.5 ,9.0 ,13.0 ,7.5 ,10.5 ,8.5 ,12.0 ,10.5 ,13.0 ,11.58 ,8.4 ,5.0 ,10.0 ,6.5 ,7.5 ,8.5 ,10.5 ,8.5 ,10.5 ,11.0 ,9.0 ,13.0),
  
  height = c(66.0, 68.0 ,64.5 ,65.0 ,70.0 ,64.0 ,70.0 ,71.0 ,72.0 ,64.0 ,74.5 ,67.0 ,71.0 ,71.0 ,77.0 ,72.0, 59.0 ,62.0 ,72.0 ,66.0 ,64.0 ,67.0 ,73.0 ,69.0 ,72.0 ,70.0 ,69.0 ,70.0),

  gender = c('F' ,'F' ,'F' ,'F' ,'M' ,'F' ,'F' ,'F' ,'M' ,'F' ,'M' ,'F' ,'M' ,'M' ,'M' ,'M' ,'F' ,'F' ,'M' ,'F' ,'F' ,'M' ,'M' ,'F' ,'M' ,'M' ,'M' ,'M')
)

file <- "shoeSizes.csv"
file.exists(file)
```

```{r}
#a. Describe the data
#The data is about the shoe sizes, the height, and the gender of the household.  
  summary(shoeSizes)
```

```{r}  
#b Create a subset by males and females with their corresponding shoe size and height.What its result? Show the R scripts.
  
  male_subset <- subset(shoeSizes, gender =="M",select = c(shoe_Size,height))
  
   female_subset <- subset(shoeSizes, gender =="F",select = c(shoe_Size,height))
   
   print(male_subset)
   print(female_subset)
```

```{r}
#c Find the mean of shoe size and height of the respondents. Write the R scripts and its result

  mean_shoeSize <- mean(shoeSizes$shoe_Size)
  mean_height <- mean(shoeSizes$height)
  
  cat(mean_shoeSize)
  cat(mean_height)

#d. Is there a relationship between shoe size and height? Why?
# yes, because shoe size generally is proportional to height

#Factors

Gender <- c("M","F","F","M")
factor_Gender <- factor(Gender)
factor_Gender
```

```{r}
#2 Construct character vector months to a factor with factor() and assign the result to factor_months_vector. Print out factor_months_vector and assert that R prints out the factor levels below the actual values.  

Months <- c("March","April","January","November","January",
"September","October","September","November","August",
"January","November","November","February","May","August",
"July","December","August","August","September","November","February","April")
factor_Months <- factor(Months)
factor_Months
```

```{r}
#3. Then check the summary() of the months_vector and factor_months_vector. | Inter-pret the results of both vectors. Are they both equally useful in this case?
  summary(factor_Months)
```

```{r}
#4 Create a vector and factor for the table below

direction_vector <- c("East","West","North")
frequency_vector <- c(1,4,3)

new_order_data <- factor(direction_vector,levels = c("East","West","North"), c(1,4,3))
print(new_order_data)
```

```{r}
#5 Enter the data below in Excel with file name = import_march.csv
#a. Import the excel file into the Environment Pane using read.table() function. Write the code.

```

```{r}
#Using Conditional Statements (IF-ELSE)
#6 Full Search
#a. Create an R Program that allows the User to randomly select numbers from 1 to 50.Then display the chosen number. If the number is beyond the range of the selected choice, it will have to display a string “The number selected is beyond the range of 1 to 50”. If number 20 is inputted by the User, it will have to display “TRUE”, otherwise display the input number.

 num <- readline(prompt= "Enter number from 1 to 50:") 
    
  paste("Your entered number is ", num)
    
  if(num == 20) {
      paste("The number you selected is beyond the range of 1 to 50")
    } else if (num <= 50){
      paste("TRUE")
    } else {
      paste(num)
    }
```

```{r}
#7. Change
#a Write a function that prints the minimum number of bills that must be paid, given the price of the snack.

minimum <- function (price) {
    bill <- price%/% 50 
    paste("The  minimum number of bills:", bill)
    }
     snackprice <- 250
     minimum(snackprice)
```

```{r}
#8 The following is each student’s math score for one semester. Based on this, answer the following questions.
#a Create a dataframe from the above table. Write the R codes and its output.
math_grades <- data.frame(
 name = c("Annie", "Thea", "Steve", "Hanna"),
     grade1 = c(85, 65, 75, 95),
     grade2 = c(65, 75, 55, 75),
     grade3 = c(85, 90, 80, 100),
     grade4 = c(100, 90, 85, 90)
)
print(math_grades)
```

```{r}
#b Without using the rowMean function, output the average score of students whose average math score over 90 points during the semester. write R code and its output
math_grades <- data.frame(
       name = c("Annie", "Thea", "Steve", "Hanna"),
       grade1 = c(85, 65, 75, 95),
       grade2 = c(65, 75, 55, 75),
       grade3 = c(85, 90, 80, 100),
       grade4 = c(100, 90, 85, 90)
     )
     print(math_grades)
     

     
  top <- math_grades[math_grades$average >= 90,]
  top
     
  if (nrow(top) > 0) {
       paste(top$name, "'s average grade this semester is", top$average)
     } else {
       paste("No students have an average math score over 90.")
       }
```

```{r}
#c Without using the mean function, output as follows for the tests in which the average score was less than 80 out of 4 tests.

test1 <- sum(math_grades$grade1) / nrow(math_grades)
test1 
     
test2 <- sum(math_grades$grade2) / nrow(math_grades)
test2 
     
test3 <- sum(math_grades$grade3) / nrow(math_grades)
test3 
     
test4 <- sum(math_grades$grade4) / nrow(math_grades)
test4
     
  if (test1 < 80) {
       paste("The 1st test was difficult")
     } else if (test2 < 80) {
       paste("The 2nd test was difficult")
     } else if (test3 < 80) {
       paste("The 3rd test was difficult")
     } else if (test4 < 80) {
       paste("The 4th test was difficult")
     } else { paste("No test had an average grade less than 80")
     } 
#d Without using the max function, output as follows for students whose highest score for a semester exceeds 90 points.     

 # annie scores
if (math_grades[1,2] > math_grades[1,3] && math_grades[1,2] > math_grades[1,4] && math_grades[1,2] > math_grades[1,5]) {
  annie <- math_grades[1,2]
} else if (math_grades[1,3] > math_grades[1,4] && math_grades[1,3] > math_grades[1,5]) {
  annie <- math_grades[1,3]
} else if (math_grades[1,4] > math_grades[1,5] && math_grades[1,2] > math_grades[1,5]) {
  annie <- math_grades[1,4]
} else {
  annie <- math_grades[1,5]
}
# thea scores
if (math_grades[2,2] > math_grades[2,3] && math_grades[2,2] > math_grades[2,4] && math_grades[2,2] > math_grades[2,5]) {
  thea <- math_grades[2,2]
} else if (math_grades[2,3] > math_grades[2,4] && math_grades[2,3] > math_grades[2,5]) {
  thea <- math_grades[2,3]
} else if (math_grades[2,4] > math_grades[2,5] && math_grades[2,2] > math_grades[2,5]) {
  thea <- math_grades[2,4]
} else {
  thea <- math_grades[2,5]
}
# steve scores
if (math_grades[3,2] > math_grades[3,3] && math_grades[3,2] > math_grades[3,4] && math_grades[3,2] > math_grades[3,5]) {
  steve <- math_grades[3,2]
} else if (math_grades[3,3] > math_grades[3,4] && math_grades[3,3] > math_grades[3,5]) {
  steve <- math_grades[3,3]
} else if (math_grades[3,4] > math_grades[3,5] && math_grades[3,2] > math_grades[3,5]) {
  steve <- math_grades[3,4]
} else {
  steve <- math_grades[3,5]}
# hanna scores
if (math_grades[4,2] > math_grades[4,3] && math_grades[4,2] > math_grades[4,4] && math_grades[4,2] > math_grades[4,5]) {
  hanna <- math_grades[4,2]
} else if (math_grades[4,3] > math_grades[4,4] && math_grades[4,3] > math_grades[4,5]) {
  hanna <- math_grades[4,3]
} else if (math_grades[4,4] > math_grades[4,5] && math_grades[4,2] > math_grades[4,5]) {
  hanna <- math_grades[4,4]
} else {
  hanna <- math_grades[4,5]
}

math_grades$highest <- c(annie, thea, steve, hanna)


above_grade_of90 <- math_grades[math_grades$highest >= 90,]


if (nrow(above_grade_of90) > 0) {
  paste(above_grade_of90$name, "'s highest grade this semester is", above_grade_of90$highest)
} else { 
paste("No students have an average math score over 90.")
}

```