---
title: "RWorksheet#4b_Parrenas"
author: "Erikka Jane Parrenas"
date: "2023-11-08"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Using Loop Function
#1. Using the for loop, create an R script that will display a 5x5 matrix as shown in Figure 1. It must contain vectorA = [1,2,3,4,5] and a 5 x 5 zero matrix.
  vectorA <- c(1, 2, 3, 4, 5)
  zeroMatrix <- matrix(0, nrow = 5, ncol = 5)


  for (i in 1:5){
  for (j in 1:5){
   
    diff <- abs(vectorA[i] - j)
   
    cat(diff, " ")
  }
  cat("\n")
  }
``` 
```{r}
#2. Print the string "*" using for() function. The output should be the same as shown in Figure
  
for(i in 1:5){
    ejp <- rep("*", i)
    print(ejp)
}
```
```{r}
#3. Get an input from the user to print the Fibonacci sequence starting from the 1st input up to 500. Use repeat and break statements. Write the R Scripts and its output.

user_input <- as.numeric(readline("Enter a number to start the Fibonacci sequence: "))


a <- 0
b <- 1

cat("Fibonacci sequence starting from", user_input, ": ")
cat(user_input, " ")


repeat {

  fiboSeq <- a + b


  if (fiboSeq > 500) {
    break
  }


  cat(fiboSeq, " ")

 
  a <- b
  b <- fiboSeq
}

         
```
```{r}
#4a. Import the data set as shown in Figure 1 you have created previously.

library(readr)
shoeSizes <- read_csv("shoeSizes.csv")
View(shoeSizes)
```

```{r}
#b. Create a subset for gender(female and male). How many observations are there in Male? How about in Female? Write the R scripts and its output.

 male <- shoeSizes[shoeSizes$gender == "M",]
    female <- shoeSizes[shoeSizes$gender == "F",]
    
    maleCount <- nrow(male)
    femaleCount <- nrow(female)
    
    cat("Numbers of male: ", maleCount, "\n")
    cat("Numbers of female: ", femaleCount, "\n")
  
```
```{r}
#c. Create a graph for the number of males and females for Household Data. Use plot(),chart type = barplot. Make sure to place title, legends, and colors. Write the R scripts and its result.
genderCount <- c(male = maleCount, female = femaleCount)
     
      barplot(genderCount, main = "Numbers of Male and Female",
              xlab = "Gender", ylab = "Numbers", col = c("blue", "magenta"),
              legend.text = TRUE, width = c(0.2, 0.2))
      legend("topright", legend = names(genderCount), col =  c("blue", "magenta"))
      
```
```{r}
#5. The monthly income of Dela Cruz family was spent
mypie <- c(60, 10, 5, 25)


pie(mypie, 
    main = "Monthly Income of Dela Cruz family",
    col = rainbow(length(mypie)),
    labels = c("60%", "10%", "5%","25%"),
    
)
legend("topright", legend = c("Food", "Electricity", "Savings", "Miscellaneous"), fill = rainbow(length(mypie)))

```
```{r}
#6.Use the iris data set

#a. Check for the structure of the data set using the str() function. Describe what you have seen in the output.

        data(iris)
        str(iris)
        
#The output shows the data's structure, which includes the variables and objects as well as the length, width, and species of the petals, sepals, and petals.

```
```{r}
#b. Create an R object that will contain the mean of the sepal.length,sepal.width,petal.length,and petal.width. What is the R script and its result?

    sepaleng <- mean(iris$Sepal.Length)
    
    sepalwid <- mean(iris$Sepal.Width)
   
    petlen <- mean(iris$Petal.Length)
    
    petwin <- mean(iris$Petal.Width)
    
    
    print(sepaleng)
    print(sepalwid)
    print(petlen)
    print(petwin)
```
```{r}
#c. Create a pie chart for the Species distribution. Add title, legends, and colors. Write the R script and its result.

      specCount <- table(iris$Species)
      
      pie(specCount,
          main = "Species",
          col = rainbow(length(specCount)),
          labels = c("setosa", "versicolor", "Virginica")
          )
      legend("topleft", legend = c("Setosa", "Versicolor", "Virginica"), fill = rainbow(length(specCount)))
          
```
```{r}
#d. Subset the species into setosa, versicolor, and virginica. Write the R scripts and show the last six (6) rows of each species.
      
      setsub <- iris[iris$Species == "setosa" | iris$Species == "Versicolor" | iris$Species == "virginica", ]
      setsub
      
      tail(setsub, 6)
      
```

```{r}
#e. Create a scatterplot of the sepal.length and sepal.width using the different species(setosa,versicolor,virginica). Add a title = “Iris Dataset”, subtitle = “Sepal width and length, labels for the x and y axis, the pch symbol and colors should be based on the species. 
   
plot(iris$Sepal.Length, iris$Sepal.Width, 
     col = as.numeric(iris$Species),  
     pch = as.numeric(iris$Species),  
     main = "Iris Dataset",
     sub = "Sepal Width and Length",
     xlab = "Sepal Length", ylab = "Sepal Width"
)

legend("topright", legend = levels(iris$Species), col = unique(as.numeric(iris$Species)), pch = unique(as.numeric(iris$Species)))

#6f. The scatterplot displays the relationship between the sepal length and width.

```
```{r}
#Basic Cleaning and Transformation of Objects
#7. Import the alexa-file.xlsx. Check on the variations. Notice that there are extra whitespaces among black variants (Black Dot, Black Plus, Black Show, Black Spot). Also on the white variants (White Dot, White Plus, White Show, White Spot).
    
library(readxl)
alexa_file <- read_excel("alexa_file.xlsx")
View(alexa_file)


```
```{r}
  library(readxl)
alexa_file$variation <- gsub("Black  Dot", "BlackDot", alexa_file$variation)
alexa_file$variation <- gsub("Black  Plus", "BlackPlus", alexa_file$variation)
  alexa_file$variation <- gsub("Black  Show", "BlackShow", alexa_file$variation)
  alexa_file$variation <- gsub("Black  Spot", "BlackSpot", alexa_file$variation)

alexa_file$variation <- gsub("White  Dot", "WhiteDot", alexa_file$variation)
alexa_file$variation <- gsub("White  Plus", "WhitePlus",alexa_file$variation)
alexa_file$variation <- gsub("White  Show", "WhiteShow", alexa_file$variation)
alexa_file$variation <- gsub("White  Spot", "WhiteSpot", alexa_file$variation)

alexa_file
```
```{r}
#b. Get the total number of each variations and save it into another object. Save the object as variations.RData. Write the R scripts. What is its result?

library("dplyr")

vari <- alexa_file %>% 
  count(alexa_file$variation)

vari
save(vari, file = "variations.RData")
```
```{r}
#c. From the variations.RData, create a barplot(). Complete the details of the chart which include the title, color, labels of each bar.
    load("variations.RData")
  vari
  namevari <- vari$`alexa_file$variation`

  ploto <- barplot(vari$n,
                     names.arg = namevari,
                     main = "Total number of each variations",
                     xlab = "Name of Variations",
                     ylab = "Total of each Variatons",
                     col = 1:16,
                     space = 0.1,
                     cex.names = 0.5,
                     las = 2)
```
```{r}
#d. Create a barplot() for the black and white variations. Plot it in 1 frame, side byside. Complete the details of the chart.

library(ggplot2)
library(magrittr)

#layout one frame
par(mfrow = c(1, 2), mar = c(2, 2, 2, 2))

Blackplot <- vari[vari$`alexa_file$variation` %in% c("Black", "BlackDot", "BlackShow", "BlackPlus", "BlackSpot"), ]

Whiteplot <- vari[vari$`alexa_file$variation` %in% c("White", "WhiteDot", "WhiteShow", "WhitePlus", "WhiteSpot"), ]

# Barplot for Black variations
Black <- barplot(height = Blackplot$n,
                names.arg = Blackplot$`alexa_file$variation`,
                col = "Black",
                main = "Black Variations",
                xlab = "Number of Variation",
                ylab = "Count",
                las = 0.0,
                cex.names = 0.4, 
		space = 0.2
)

# Barplot for White variations
White <- barplot(height = Whiteplot$n,
                 names.arg = Whiteplot$`alexa_file$variation`,
                 col = "White",
                 main = "White Variations",
                 xlab = "Number of Variation",
                 ylab = "Count",
                 las = 0.0,
                 cex.names = 0.4,
                 space = 0.2
)


```
